### ISSUE TITLE
Responsive version

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/vitimas-da-intolerancia#13]
The extremely simple CSS for this MVP is not responsive. Any contribution in this direction is welcomed (we don't have any UI/layout yet though).

**Comment by humrochagf** [comment]
I can help with that, until tomorrow morning i will send a PR

**Comment by humrochagf** [comment]
Since the website is published i made a first pr #15 with the mobile version.
There is some improvements with some css class names, and with the footer but its usable on mobile
