### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by qgustavor** [okfn-brasil/vitimas-da-intolerancia#18]
The server hosting vitimasdaintolerancia.org supports HTTPS and have a valid certificate from Let's Encrypt, but there are some issues:

- [x] It's not redirecting to https://vitimasdaintolerancia.org/
- [ ] There's mixed content from `static.nsctotal.com.br`, `www.diarioonline.com.br`, `odiarionacional.org` (those domains supports HTTPS) and `piauihoje.com` (which don't support HTTPS due a server misconfiguration)
- [x] The website URL on [the repository home page](https://github.com/okfn-brasil/vitimas-da-intolerancia) points to http://vitimasdaintolerancia.org/

[HTTPS is important](https://doesmysiteneedhttps.com/). Even if there's no forms in the website it ensures integrity of data, preventing MITM attacks like adding advertisements, changing content or filtering news against someone.

**Comment by cuducos** [comment]
Many thanks, @qgustavor. I edited you post to convert your list into a TODO list, ok?

Regarding number 1: we're changing servers and that should be fixed afterwards

Regarding number 2: what do you suggest in those cases?

Regarding number 3: fixing now, gonna cross that in a minute.

**Comment by qgustavor** [comment]
That's ok. About the mixed content issue can you rehost images?

**Comment by cuducos** [comment]
> About the mixed content issue can you rehost images?

Yes we can. But definitively it's not a priority at the moment. Is this the only alternative?

**Comment by qgustavor** [comment]
Having images being loaded via HTTP allows those be changed on a MITM attack, but it's not bad like adding adversiments or changing textual content. Rehosting would be a good thing to avoid issues with websites that block hotlinking.
Can you rehost images hosted on websites which don't support HTTPS (at the moment only one hosted on piauihoje.com) and fix the other images to point to HTTPS? If not then I don't have other idea. At least, the risk was reduced by loading the page over HTTPS.

**Comment by cuducos** [comment]
Some ideas @turicas and I speculated:

* Automate image generation using [Imgur](https://api.imgur.com/)
* Spin up a [thumbor](http://thumbor.org/) instance

**Comment by cuducos** [comment]
I'm gonna close this issue and open a more specific one (related to external images and HTTPS). Feel free to jump in, @qgustavor ; )
