### ISSUE TITLE
Use target=_blank on stories urls

### ISSUE THREAD

**Issue by ellisonleao** [okfn-brasil/vitimas-da-intolerancia#9]
https://github.com/okfn-brasil/violencia-nao-tem-partido/blob/master/violence/templates/index.html#L32

Maybe we can add `_blank` targets on links for a better user experience

**Comment by ellisonleao** [comment]
I think the only "recommendation" for use `_blank` targets are for when your link points to another website. But then again, this is totally a personal choice. There are several reasons for [use or not](https://css-tricks.com/use-target_blank/)

**Comment by kishan3** [comment]
> https://github.com/okfn-brasil/violencia-nao-tem-partido/blob/master/violence/templates/index.html#L32
> 
> Maybe we can add `_blank` targets on links for a better user experience

The link is broken. 404 error

**Comment by cuducos** [comment]
We started using Jinja2 `extends` so we changed a bit the HTML files. But @ellisonleao was referring to external links to news outlet stories.
